### ISSUE TITLE
Issue Title
Fixing the frontend/homepage of the dasboard.   

### ISSUE THREAD

**Issue by dylzeee** [StartBootstrap/startbootstrap-sb-admin#147]
Get the homepage content area of the dashboard fully operational with real incoming data from API and Wordpress functions.

Issues.

1. Fix the cards. Currently broken. Need to pass the function data to the twig template and add conditionals to add hard-coded data if empty or null

2. Make the graphs operational with real JSON data from API response

3. Fix the tables to show real ticket data and in the case of no tickets, display an 'open new ticket' button.

**Comment by davidtmiller** [comment]
From a functionality standpoint, these are things that would need to be done on the user end rather than included within the base template.
